% Decompose Signal using the MODWT
% Generated by MATLAB(R) 9.9 and Wavelet Toolbox 5.5.
% Generated on: 15-Sep-2021 04:59:02
% Logical array for selecting reconstruction elements
function clnSig = waveletFilter1(rawSig)
levelForReconstruction = [true, true, true, true, true, true, false, false, false, false, false];
% Perform the decomposition using modwt
wt = modwt(rawSig, 'sym4', 10);
% Construct MRA matrix using modwtmra
mra = modwtmra(wt, 'sym4');
% Sum along selected multiresolution signals
clnSig = sum(mra(levelForReconstruction,:),1);
end
